# Generated by Django 5.0.6 on 2024-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(default='Unknown', max_length=255)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('medical_issues', models.TextField(blank=True, null=True)),
                ('medication_amount', models.IntegerField(default=0)),
                ('women_bool', models.BooleanField(default=False)),
                ('child_bool', models.BooleanField(default=False)),
                ('baby_bool', models.BooleanField(default=False)),
                ('pet_bool', models.BooleanField(default=False)),
                ('blind_bool', models.BooleanField(default=False)),
                ('deaf_bool', models.BooleanField(default=False)),
                ('wheelchair_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
