# Generated by Django 5.0.6 on 2024-06-14 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_users_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='family_size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
