# Generated by Django 5.0.6 on 2024-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_users_family_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='family_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
