# Generated by Django 5.0.6 on 2024-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_users_latitude_users_longitude_alter_users_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blind_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='deaf_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pet_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='wheelchair_bool',
            field=models.BooleanField(default=False),
        ),
    ]
